/*
** PRIVILÉGIOS DUPLICADOS
*/

DELETE FROM USERACCESS WHERE CODUSUARIO = 0 OR CODRESOURCE = 0;

UPDATE CLIENTES SET CODIGO = 15 WHERE CODIGO = 0;

INSERT INTO SCRIPTVER(NUMERO, DATA) VALUES (468, CURRENT_TIMESTAMP);
COMMIT;
